# Copyright (c) 2019, Fuzhou Rockchip Electronics Co., Ltd
# Released under the MIT license (see COPYING.MIT for the terms)

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	        ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rock2f"
BBFILE_PATTERN_rock2f := "^${LAYERDIR}/"
BBFILE_PRIORITY_rock2f = "10"

LAYERDEPENDS_rock2f = "core"
LAYERVERSION_rock2f = "1"
LAYERSERIES_COMPAT_rock2f = "scarthgap"

INHERIT:append = " rockchip-image"


ERROR_QA:remove = "patch-status"

#IMAGE_INSTALL:append = " android-tools android-tools-conf-rockchip"
#PREFERRED_PROVIDER_android-tools-conf = "android-tools-conf-rockchip"

#USB_DEBUGGING_ENABLED = "1"

LICENSE_FLAGS_ACCEPTED:append = " commercial"

#SYSTEMD_AUTO_ENABLE = "enable"
#SYSTEMD_AUTO_ENABLE:kodi-systemd-service = "enable"

INIT_MANAGER = "systemd"
SYSTEMD_AUTO_ENABLE = "enable"
IMAGE_INSTALL:append = " util-linux-agetty"
EXTRA_IMAGE_FEATURES += "debug-tweaks"

IMAGE_INSTALL:append = " \
    mesa-demos \
    glmark2 \
    libdrm-tests \
    kmscube \
"

# Abilita il driver Lima (GPU) e kmsro (per il display)
PACKAGECONFIG:append:pn-mesa = " lima kmsro"

# Specifica i driver DRI da generare
PACKAGECONFIG:append:pn-mesa = " gallium"

IMAGE_INSTALL:append= " \
    kernel-modules \
    rkwifibt-firmware \
"

RK_WIFIBT_RRECOMMENDS = " \
    rkwifibt-firmware-aic8800d80-usb \
"

IMAGE_INSTALL:append = " \
    iw \
    wpa-supplicant \
"