# Copyright (c) 2019, Fuzhou Rockchip Electronics Co., Ltd
# Released under the MIT license (see COPYING.MIT for the terms)

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	        ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rock2f"
BBFILE_PATTERN_rock2f := "^${LAYERDIR}/"
BBFILE_PRIORITY_rock2f = "10"

LAYERDEPENDS_rock2f = "core"
LAYERVERSION_rock2f = "1"
LAYERSERIES_COMPAT_rock2f = "scarthgap"